import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainProvider } from "./MainProvider";
import Sider from "./Sider";
import { dbConfig } from "./utils/dbConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-h-full flex max-md:block">
          <Sider />
          <div className="w-full">
            <div className={`px-10 pb-14 md:px-8 `}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
